version: "3.9"

services:
  pg_vector:
    image: pgvector/pgvector:0.6.2-pg15
    container_name: pg_vector
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
